name: Birthday Confetti

on:
  schedule:
    # Runs every 4 hours except during critical transition period
    - cron: '0 */4 * * *'
    
    # Extra runs around midnight to ensure precise timing
    - cron: '55 23 11 7 *'  # July 11 at 23:55 UTC (02:55 July 12 Nairobi)
    - cron: '0 0 12 7 *'    # July 12 at 00:00 UTC (03:00 July 12 Nairobi)
    - cron: '55 23 12 7 *'  # July 12 at 23:55 UTC (02:55 July 13 Nairobi)
    - cron: '0 0 13 7 *'    # July 13 at 00:00 UTC (03:00 July 13 Nairobi)
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pytz
        run: pip install pytz

      - name: Update README
        run: python .github/scripts/update_confetti.py

      - name: Commit changes
        if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update birthday confetti" || echo "No changes to commit"
          git push
