name: Birthday Confetti

on:
  schedule:
    # Runs every 4 hours to cover all timezones
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pytz
        run: pip install pytz

      - name: Update README
        run: python .github/scripts/update_confetti.py

      - name: Commit changes
        if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update birthday confetti" || echo "No changes to commit"
          git push
